defaults: &defaults
  docker:
    - image: mercari/appengine-go:slim
  working_directory: /go/src/github.com/morikuni/gaelog

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: init
          command: make init
      - run:
          name: deps
          command: make deps
      - run:
          name: test
          command: make test
      - run:
          name: coverage
          command: go test -coverpkg=. -covermode=atomic -coverprofile=coverage.txt
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)